# Human-medicine parallel for each veterinary question.
# Every trial name, figure and direction below was verified against Europe PMC /
# Crossref primary records before being written here.
# dirn: same | opposite | absent | ahead   (relative to the veterinary position)
HUMAN = {
"Pimobendan in preclinical stage B2 disease": dict(dirn="absent",
 txt="No equivalent trial. Inotropes are not administered to humans before symptoms appear.",
 ref=""),
"Pimobendan in congestive heart failure": dict(dirn="opposite",
 txt="Oral PDE3 inhibitors <b>increased</b> mortality. Milrinone by 28% (p&nbsp;=&nbsp;0.038); vesnarinone dose-dependently, 22.9% vs 18.9% deaths, while improving quality of life.",
 ref="PROMISE 1991 &middot; VEST 1998"),
"ACE inhibitors before heart failure": dict(dirn="same",
 txt="Enalapril in asymptomatic low ejection fraction reduced progression to heart failure by 29%, but <b>did not reduce mortality</b> (p&nbsp;=&nbsp;0.30).",
 ref="SOLVD-Prevention 1992"),
"Spironolactone added to standard heart-failure therapy": dict(dirn="same",
 txt="Spironolactone reduced mortality by 30% in severe heart failure (35% vs 46% deaths); eplerenone reproduced the effect in mild disease.",
 ref="RALES 1999 &middot; EMPHASIS-HF 2011"),
"Spironolactone with benazepril to delay the onset of heart failure": dict(dirn="absent",
 txt="No equivalent. The corresponding human trials enrolled symptomatic patients.",
 ref=""),
"Furosemide dose and dosing frequency in stage C disease": dict(dirn="absent",
 txt="Also sparse in humans. Loop diuretic dosing remains largely conventional.", ref=""),
"Pimobendan in preclinical dilated cardiomyopathy (Dobermanns)": dict(dirn="opposite",
 txt="No preclinical equivalent. In symptomatic human disease, oral inotropes reduced survival.",
 ref="PROMISE 1991"),
"Diet change and taurine in diet-associated dilated cardiomyopathy": dict(dirn="absent",
 txt="No equivalent condition or trial.", ref=""),
"Screening intervals in at-risk breeds": dict(dirn="absent",
 txt="Family screening in inherited cardiomyopathy is guideline-driven, not trial-driven.", ref=""),
"Clopidogrel to prevent recurrent arterial thromboembolism": dict(dirn="opposite",
 txt="Antiplatelet therapy is the <b>fallback</b>, not the preferred option in humans. Anticoagulation beat clopidogrel plus aspirin (RR 1.44 favouring anticoagulation); across trials antiplatelets cut stroke 22%, warfarin 64%.",
 ref="ACTIVE-W 2006 &middot; Hart 2007"),
"Atenolol in preclinical hypertrophic cardiomyopathy": dict(dirn="opposite",
 txt="No outcome trial in HCM anywhere. In <b>non-obstructive</b> HCM, which is the phenotype most feline patients have, a placebo-controlled crossover found bisoprolol reduced exercise capacity and quality of life and raised NT-proBNP and atrial size.",
 ref="Bjerregaard 2026 &middot; TEMPO 2021 &middot; MAPLE-HCM 2025"),
"Pimobendan in feline congestive heart failure": dict(dirn="opposite",
 txt="Oral inotropes increased mortality in human heart failure.", ref="PROMISE 1991"),
"Rapamycin (sirolimus) in subclinical hypertrophic cardiomyopathy": dict(dirn="ahead",
 txt="<b>No human trial exists in HCM.</b> The only randomised human data are small, mixed studies of left ventricular mass in transplant recipients, confounded by withdrawal of another drug. Here the veterinary trial is ahead of the human literature.",
 ref="Paoletti 2012 &middot; RADTAC 2021"),
"Any therapy that delays the onset of heart failure in hypertrophic cardiomyopathy": dict(dirn="absent",
 txt="Equally unanswered in humans; no trial has tested delay of heart-failure onset in hypertrophic cardiomyopathy.", ref=""),
"Do glucocorticoids precipitate congestive heart failure?": dict(dirn="opposite",
 txt="Prednisone is used to <b>increase</b> diuresis in heart failure, and a randomised pilot in acute heart failure found fewer 90-day events (HR 0.31). Large observational cohorts do associate high-dose steroids with cardiovascular events (RR 2.56), heavily confounded by indication.",
 ref="Liu 2006 &middot; CORTAHF 2024 &middot; Wei 2004"),
"Torasemide as an alternative to furosemide (dogs)": dict(dirn="same",
 txt="Concordant, in a much larger trial. No difference in all-cause mortality across 2,859 patients (HR 1.02).",
 ref="TRANSFORM-HF 2023"),
"Sacubitril&ndash;valsartan (ARNi) in congestive heart failure": dict(dirn="same",
 txt="Among the strongest results in cardiology. Cardiovascular death or heart-failure hospitalisation fell by 20% and all-cause death by 16% against an active comparator, in 8,442 patients.",
 ref="PARADIGM-HF 2014"),
"Dietary sodium restriction": dict(dirn="same",
 txt="Tested directly, with a neutral result. Sodium restriction made no difference to death or hospitalisation (HR 0.89, not significant).",
 ref="SODIUM-HF 2022"),
"Exercise restriction after diagnosis": dict(dirn="opposite",
 txt="Human patients with heart failure are prescribed the opposite. Supervised aerobic <b>training</b> was safe in advanced disease; the benefit reached significance only after adjustment.",
 ref="HF-ACTION 2009"),
"Rate control in atrial fibrillation: diltiazem with digoxin versus monotherapy": dict(dirn="same",
 txt="Lenient rate control (under 110 bpm at rest) was not inferior to strict, and far easier to achieve.",
 ref="RACE II 2010"),
"Sotalol versus mexiletine&ndash;atenolol in Boxer arrhythmogenic cardiomyopathy": dict(dirn="opposite",
 txt="Suppressing ectopy after myocardial infarction with flecainide or encainide <b>increased total mortality</b>, 7.7% vs 3.0%, relative risk 2.5. The drugs achieved precisely what the Holter was asked to show.",
 ref="CAST 1989/1991"),
"When to treat ventricular arrhythmias in asymptomatic dogs": dict(dirn="opposite",
 txt="Answered, and answered against treatment. Treating asymptomatic ectopy after myocardial infarction raised mortality two and a half times, with no signal on any intermediate measure.",
 ref="CAST 1989/1991"),
"Holter thresholds that predict sudden death": dict(dirn="absent",
 txt="Human risk stratification uses different tools and is itself contested.", ref=""),
"Does preclinical pimobendan shorten survival once heart failure develops?": dict(dirn="opposite",
 txt="The concern has a precedent. Oral inotropes improved symptom scores in humans while shortening survival.",
 ref="PROMISE 1991 &middot; VEST 1998"),
}

HUMAN_REFS = [
 'PROMISE. Packer M, Carver JR, Rodeheffer RJ, et al. Effect of oral milrinone on mortality in severe chronic heart failure. <em>N Engl J Med.</em> 1991;325:1468&ndash;1475. PMID 1944425.',
 'VEST. Cohn JN, Goldstein SO, Greenberg BH, et al. A dose-dependent increase in mortality with vesnarinone among patients with severe heart failure. <em>N Engl J Med.</em> 1998;339:1810&ndash;1816. PMID 9854116.',
 'SOLVD-Prevention. SOLVD Investigators. Effect of enalapril on mortality and the development of heart failure in asymptomatic patients with reduced left ventricular ejection fractions. <em>N Engl J Med.</em> 1992;327:685&ndash;691. PMID 1463530.',
 'RALES. Pitt B, Zannad F, Remme WJ, et al. The effect of spironolactone on morbidity and mortality in patients with severe heart failure. <em>N Engl J Med.</em> 1999;341:709&ndash;717. PMID 10471456.',
 'EMPHASIS-HF. Zannad F, McMurray JJV, Krum H, et al. Eplerenone in patients with systolic heart failure and mild symptoms. <em>N Engl J Med.</em> 2011;364:11&ndash;21. PMID 21073363.',
 'PARADIGM-HF. McMurray JJV, Packer M, Desai AS, et al. Angiotensin&ndash;neprilysin inhibition versus enalapril in heart failure. <em>N Engl J Med.</em> 2014;371:993&ndash;1004. PMID 25176015.',
 'TRANSFORM-HF. Mentz RJ, Anstrom KJ, Eisenstein EL, et al. Effect of torsemide vs furosemide after discharge on all-cause mortality in patients hospitalized with heart failure. <em>JAMA.</em> 2023;329:214&ndash;223. PMID 36648467.',
 'DOSE. Felker GM, Lee KL, Bull DA, et al. Diuretic strategies in patients with acute decompensated heart failure. <em>N Engl J Med.</em> 2011;364:797&ndash;805. PMID 21366472.',
 'SODIUM-HF. Ezekowitz JA, Colin-Ramirez E, Ross H, et al. Reduction of dietary sodium to less than 100 mmol in heart failure. <em>Lancet.</em> 2022;399:1391&ndash;1400. PMID 35381194.',
 'HF-ACTION. O&rsquo;Connor CM, Whellan DJ, Lee KL, et al. Efficacy and safety of exercise training in patients with chronic heart failure. <em>JAMA.</em> 2009;301:1439&ndash;1450. PMID 19351941.',
 'CAST. CAST Investigators. Preliminary report: effect of encainide and flecainide on mortality in a randomized trial of arrhythmia suppression after myocardial infarction. <em>N Engl J Med.</em> 1989;321:406&ndash;412. PMID 2473403. Full report: Echt DS, Liebson PR, Mitchell LB, et al. <em>N Engl J Med.</em> 1991;324:781&ndash;788. PMID 1900101.',
 'RACE II. Van Gelder IC, Groenveld HF, Crijns HJGM, et al. Lenient versus strict rate control in patients with atrial fibrillation. <em>N Engl J Med.</em> 2010;362:1363&ndash;1373. PMID 20231232.',
 'ACTIVE-W. ACTIVE Writing Group. Clopidogrel plus aspirin versus oral anticoagulation for atrial fibrillation. <em>Lancet.</em> 2006;367:1903&ndash;1912. PMID 16765759.',
 'Hart RG, Pearce LA, Aguilar MI. Meta-analysis: antithrombotic therapy to prevent stroke in patients who have nonvalvular atrial fibrillation. <em>Ann Intern Med.</em> 2007;146:857&ndash;867. PMID 17577005.',
 'TEMPO. Dybro AM, Rasmussen TB, Nielsen RR, et al. Randomized trial of metoprolol in patients with obstructive hypertrophic cardiomyopathy. <em>J Am Coll Cardiol.</em> 2021;78:2505&ndash;2517. PMID 34915981.',
 'MAPLE-HCM. Garcia-Pavia P, Maron MS, Masri A, et al. Aficamten or metoprolol monotherapy for obstructive hypertrophic cardiomyopathy. <em>N Engl J Med.</em> 2025;393:949&ndash;960. PMID 40888697.',
 'Bjerregaard L, Dybro AM, Saaby L, et al. Beta-blocker versus calcium-channel blocker in nonobstructive hypertrophic cardiomyopathy: a randomized triple-crossover physiologic trial. <em>J Am Coll Cardiol.</em> 2026;87:1063&ndash;1083. PMID 41778690.',
 'CORTAHF. Cotter G, Davison BA, Freund Y, et al. Burst steroid therapy for acute heart failure. <em>Eur J Heart Fail.</em> 2024;26:2282&ndash;2292. PMID 39211989.',
 'Wei L, MacDonald TM, Walker BR. Taking glucocorticoids by prescription is associated with subsequent cardiovascular disease. <em>Ann Intern Med.</em> 2004;141:764&ndash;770. PMID 15545676.',
 'Paoletti E, Marsano L, Bellino D, et al. Effect of everolimus on left ventricular hypertrophy of de novo kidney transplant recipients. <em>Transplantation.</em> 2012;93:503&ndash;508. PMID 22318246.',
 'RADTAC. Anthony C, Imran M, Pouliopoulos J, et al. Everolimus for the prevention of calcineurin-inhibitor-induced left ventricular hypertrophy after heart transplantation. <em>JACC Heart Fail.</em> 2021;9:301&ndash;313. PMID 33795116.',
]
